/// Build script — auto-bundles all `i18n/*.ftl` files at compile time.
///
/// Generates `$OUT_DIR/bundled_langs.rs`:
///   `pub const BUNDLED_LANGS: &[(&str, &str)]`
/// where each entry is `(lang_code, ftl_content)`.
///
/// Drop a new `.ftl` file into `i18n/` and the next build includes it
/// automatically — no manual code changes required.
use std::{env, fmt::Write as _, fs, path::Path};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let lang_dir = Path::new(&manifest_dir).join("i18n");

    // Re-run whenever any FTL file is added, removed, or changed.
    println!("cargo:rerun-if-changed=i18n/");
    // Re-run when the compiled-in lang CID map is updated.
    println!("cargo:rerun-if-changed=src/i18n.yaml");

    let mut entries: Vec<(String, String)> = Vec::new();

    let read_dir =
        fs::read_dir(&lang_dir).unwrap_or_else(|e| panic!("cannot read i18n/ directory: {e}"));

    for entry in read_dir {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("ftl") {
            continue;
        }
        let code = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap()
            .to_string();
        // Use the canonical absolute path so include_str! works from OUT_DIR.
        let abs = path
            .canonicalize()
            .unwrap_or_else(|e| panic!("cannot canonicalize {}: {e}", path.display()));
        let abs_str = abs.to_str().unwrap().replace('\\', "/"); // forward slashes on all platforms
        entries.push((code, abs_str));
    }

    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut src = String::from(
        "/// Auto-generated by build.rs — do not edit by hand.\n\
         /// Each entry is `(lang_code, ftl_content)`.\n\
         /// To add a language: drop a `lang/<code>.ftl` file with a\n\
         /// `lang-name = <autonym>` key and rebuild.\n\
         pub const BUNDLED_LANGS: &[(&str, &str)] = &[\n",
    );
    for (code, path) in &entries {
        writeln!(src, "    (\"{code}\", include_str!(\"{path}\")),").unwrap();
    }
    src.push_str("];\n");

    let out_dir = env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("bundled_langs.rs");
    fs::write(&out_path, src).unwrap_or_else(|e| panic!("cannot write bundled_langs.rs: {e}"));
}
